// --- PLACE DATABASE (雙語映射字典) ---
// 鍵值 (Key) = data.js 中的顯示名稱 (繁體中文或品牌原名)，保持高可讀性
// query = 傳給 Google Maps API 搜尋的當地精確名稱 (日文)，確保搜尋精準度
// placeId = 跑完 Python 後填入的精確 ID

const placeDB = {
    "南房總美爵溫泉度假酒店": { query: "グランドメルキュール南房総リゾート＆スパ", placeId: "ChIJoeCPkdP3F2ARBVkncc011Ag" },
    "東京台場希爾頓酒店": { query: "ヒルトン東京お台場", placeId: "ChIJgUqLrh2KGGARehtBcuiZ4Zw" },
    "品川王子大飯店": { query: "品川プリンスホテル", placeId: "ChIJpw8ZYFeKGGARsAlZkzP5KnY" },
    "明治神宮": { query: "明治神宮", placeId: "ChIJ5SZMmreMGGARcz8QSTiJyo8" },
    "品川神社": { query: "品川神社", placeId: "ChIJqUXtB2eKGGAR5CmAxvDOPOs" },
    "江戶城 (皇居外苑)": { query: "江戸城跡 (皇居東御苑)", placeId: "ChIJxYNOEQ2MGGARCs3aknmjFOY" },
    "成田山新勝寺": { query: "成田山新勝寺", placeId: "ChIJaVf1FhCLImARQrmJujm0uwk" },
    "台場海濱公園": { query: "お台場海浜公園", placeId: "ChIJ18IK6x2KGGARKTc2yLS-030" },
    "台場海濱地區": { query: "お台場海浜公園", placeId: "ChIJ18IK6x2KGGARKTc2yLS-030" },
    "道の駅 富浦 枇杷俱樂部": { query: "道の駅とみうら 枇杷倶楽部", placeId: "ChIJ-Vz5c-n3F2AR1LLf5rw-1zg" },
    "SHIBUYA SKY": { query: "SHIBUYA SKY (渋谷スカイ)", placeId: "ChIJ4Rr2JWiLGGARcyRSHuZ-9G8" },
    "秋葉原電器街": { query: "秋葉原電気街", placeId: "ChIJZzSYoB2MGGARfBcicn7sx28" },
    "高輪カネオビル (TS公司)": { query: "高輪カネオビル", placeId: "ChIJlcMmxVCKGGARywnPAvYRKGU" },
    "成田機場": { query: "成田国際空港 第1ターミナル", placeId: "" },
    "彩虹大橋": { query: "レインボーブリッジ", placeId: "ChIJbWVFlTCKGGARr5l6ox-7_CA" },
    "台場富士電視台": { query: "フジテレビ本社ビル", placeId: "ChIJQQ6UsPeJGGAR3LFE4U43_NQ" },
    "松屋 桃園機場周邊店": { query: "松屋 桃園空港", placeId: "ChIJTVJZVQAfaDQRy3PA9s0VaxM" },
    "松屋 台場店": { query: "松屋 お台場店", placeId: "ChIJi6u-6faJGGARCnNNituDGnY" },
    "築地玉壽司 台場店": { query: "築地玉寿司 お台場", placeId: "ChIJT0hobFKLGGARiejJQ-gYVMM" },
    "Tully's Coffee 台場店": { query: "タリーズコーヒー デックス東京ビーチ店", placeId: "ChIJVVVpguCIGGARhDGmK3RSeh8" },
    "邁泉豬排 青山本店": { query: "とんかつ まい泉 青山本店", placeId: "ChIJa2mnui2NGGAR7z4tvWkl7HM" },
    "くら寿司 台場店": { query: "くら寿司 アクアシティお台場店", placeId: "ChIJ72Yrb2WJGGARfTaQyTm265w" },
    "つばめグリル 品川駅前店": { query: "つばめグリル 品川駅前店", placeId: "ChIJ1fkWHFqKGGARFuZLuCcpQgo" },
    "Blue Bottle 品川店": { query: "ブルーボトルコーヒー 品川カフェ", placeId: "ChIJN4ZUl1qKGGARwMvhBrmPtwQ" },
    "TOKYO 豚骨 BASE (ecute品川)": { query: "TOKYO豚骨BASE MADE by 一風堂 エキュート品川店", placeId: "ChIJBe0NY1qKGGARqzyrxpDl5Mw" },
    "Starbucks 品川 Prince Hotel 店": { query: "スターバックス コーヒー 品川プリンスホテル店", placeId: "ChIJgeIVSluKGGAR-YL2ropUi5o" },
    "澀谷 Scramble Square 美食街定食": { query: "渋谷スクランブルスクエア", placeId: "ChIJscDhJ4SLGGARbx0GlzPi9ng" },
    "叙々苑 品川": { query: "叙々苑 品川プリンスホテル店", placeId: "ChIJS00JW1eKGGARrb-vKf1QBpA" },
    "すき家 品川東口店": { query: "すき家 品川東口店", placeId: "ChIJr0Nw1n2KGGARc7CG2jYedJM" },
    "Denny's 秋葉原店": { query: "デニーズ 秋葉原店", placeId: "ChIJc1WNFqiOGGARWBuZ6oFippI" },
    "吉野家 品川站前店": { query: "吉野家 品川駅高輪口店", placeId: "ChIJQU9wy1qKGGARt0D-UIXcOSM" },
    "Starbucks 台場 Aqua City 店": { query: "スターバックス コーヒー アクアシティお台場店", placeId: "ChIJa51BO_aJGGARO7FatsH7D_I" },
    "Shibuya Sky 酒吧": { query: "Paradise Lounge 渋谷スカイ", placeId: "ChIJ8WnpNtuLGGAR2AaaGW5Fzxs" },
    "7-Eleven 南房總富浦多田良店": { query: "セブン-イレブン 南房総富浦多田良店", placeId: "ChIJr1QNqtv3F2ARR1sxDYdztIA" },
    "Lawson お台場海濱公園前店": { query: "ローソン お台場海浜公園前店", placeId: "ChIJXch28vOJGGARKcycQH2pSSw" },
    "マツモトキヨシ Aqua City店": { query: "マツモトキヨシ アクアシティお台場店", placeId: "ChIJueEOyl2JGGARrcXYQWuecWc" },
    "7-Eleven 品川站新高輪店": { query: "セブン-イレブン 品川プリンスホテル店", placeId: "ChIJP6hsV1eKGGARhxVaLjJiXKA" },
    "Bic Camera 有樂町店": { query: "ビックカメラ 有楽町店", placeId: "ChIJ0dtyq_qLGGARUzYbCCXz1Ic" },
    "ecute 品川": { query: "エキュート品川", placeId: "ChIJiWgSY1qKGGARhSiW7q6hp1Q" },
    "atré 品川": { query: "アトレ品川", placeId: "ChIJXZQ8lFqKGGARnG8rm_m6DUw" },
};
